/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DappInterfaceMulticall } from "./DappInterfaceMulticall";
export type { IMulticall } from "./IMulticall";
export type { Multicall } from "./Multicall";

export { DappInterfaceMulticall__factory } from "./factories/DappInterfaceMulticall__factory";
export { IMulticall__factory } from "./factories/IMulticall__factory";
export { Multicall__factory } from "./factories/Multicall__factory";
